# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
                ('type', models.CharField(choices=[('classroom', 'Classroom'), ('gym', 'Gym')], default='classroom', max_length=16)),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacity')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Building')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
