version: '3'
services:
  web:
    image: django_school
    working_dir: /app/
    ports:
     - "8000:8000"
    volumes:
     - ./:/app
    links:
     - db
  db:
    image: postgres
  node:
    image: "node"
    working_dir: /app/frontend/
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app/
    ports:
      - "8080:8080"
    command: "npm start"
  
