# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'subject enrolment',
                'verbose_name_plural': 'subject enrolments',
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField()),
                ('per_week', models.IntegerField(default=0, verbose_name='lessons per week')),
                ('duration', models.IntegerField(default=45, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'Subject template',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrolment',
            fields=[
                ('subjectenrolment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.SubjectEnrolment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
            bases=('subject.subjectenrolment',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjecttemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.SubjectTemplate')),
                ('students', models.ManyToManyField(related_name='subjects', through='subject.StudentEnrolment', to='account.Student', verbose_name='students')),
            ],
            options={
                'verbose_name': 'Subject',
            },
            bases=('subject.subjecttemplate',),
        ),
        migrations.CreateModel(
            name='TeacherEnrolment',
            fields=[
                ('subjectenrolment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subject.SubjectEnrolment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher')),
            ],
            bases=('subject.subjectenrolment',),
        ),
        migrations.AddField(
            model_name='subjectenrolment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', through='subject.TeacherEnrolment', to='account.Teacher', verbose_name='teachers'),
        ),
    ]
