# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectenrolment',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='subjectenrolment',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
